spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: coincontroltcc@gmail.com
    password: cxlg aouf mydt vnmn
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/despesas_financas_tcc?useTimezone=true&serverTimezone=UTC
    username: root
    password: admin123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
jwt:
  secret: VkRGU1JsTXdkRVpVYTFaSlZsVXhRMVF3YkZCVVJXeFBVMFZGUFE9PQ==
  expiration: 2
  expiration-email: 15


