spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: coincontroltcc@gmail.com
    password: cxlg aouf mydt vnmn
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.201:3306/coincontrol
    username: root
    password: teste1095
  jpa:
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
jwt:
  secret: VkRGU1JsTXdkRVpVYTFaSlZsVXhRMVF3YkZCVVJXeFBVMFZGUFE9PQ==
  expiration: 24
  expiration-email: 15


